### ISSUE TITLE
Add to the Nexus Exchange

### ISSUE THREAD

**Issue by DarthHater** [mjmbischoff/nexus-blobstore-swift#1]
Hi there!

You can add this to the Nexus Exchange:

https://community.sonatype.com/c/exchange

If you create an account there and open a draft, fill it out, etc... it will show up at:

https://my.sonatype.com/exchange/

This should help people find your plugin :)

Cheers,
Jeffry

**Comment by mjmbischoff** [comment]
add it under https://community.sonatype.com/t/openstack-swift-blobstore/1854, 

thank you for pointing this out.
